REQM/Controllers/Product/RepDetailedController.cs
using REQM.Domain;
using REQM.Helper;
using REQM.Models;
using REQM.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace REQM.Controllers
{
    public class RepDetailedController : Controller
    {

        private RepDetailedService DBCRUD = new RepDetailedService();

        // GET: RepDetailed
        [Authentication]
        public ActionResult Index()
        {
            return View(DBCRUD.GetRepDetaileds());
        }

        #region  创建
        [Authentication]
        public ActionResult Create(string Id)
        {
            //将ProductId通过model传到前端
            RepDetailedModel model = new RepDetailedModel();
            model.ProductId = Id;
            //返回功能性需求Model
            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public ActionResult Create(RepDetailedModel repDetailed)
        {
            if (ModelState.IsValid)
            {
                repDetailed.RepDetailedId = Guid.NewGuid().ToString();
                repDetailed.CreateAt = DateTime.Now;
                string userId = HttpContext.Session["UserId"] as string;
                repDetailed.UserId = userId;
                //将Models类转换成Domain类
                RepDetailed toEntity = repDetailed.ToEntity();
                DBCRUD.Create(toEntity);
                return RedirectToAction("Details", "ProductInfo", new { id = repDetailed.ProductId });
            }
            return View(repDetailed);
        }
        #endregion

        #region 编辑
        [Authentication]
        public ActionResult Edit(string Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepDetailed repDetailed = DBCRUD.GetRepDetailedById(Id);
            return View("Edit", repDetailed.ToModel());
        }

        [ValidateInput(false)]
        [Authentication]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RepDetailedModel repDetailed)
        {
            if (ModelState.IsValid)
            {
                repDetailed.UpdateAt = DateTime.Now;
                string userId = HttpContext.Session["UserId"] as string;
                repDetailed.Reviser = userId;
                //将Models类转换成Domain类
                RepDetailed toEntity = repDetailed.ToEntity();
                DBCRUD.Update(toEntity);
                return RedirectToAction("Details", "ProductInfo", new { id = repDetailed.ProductId });
            }
            return View(repDetailed);
        }
        #endregion

        /// <summary>
        /// 删除一条记录
        /// </summary>
        /// <param name="id">记录Id</param>
        /// <returns></returns>
        
        [Authentication]
        public ActionResult Delete(string Id)
        {

            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //获取删除的对象实体
            RepDetailed repDetailed = DBCRUD.GetRepDetailedById(Id);
            //删除数据库记录
            DBCRUD.Delete(Id);
            //返回上个界面
            return RedirectToAction("Details", "ProductInfo", new { id = repDetailed.ProductId });
        }


        [Authentication]
        public ActionResult Details(string Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepDetailed repDetailed = DBCRUD.GetRepDetailedById(Id);
            return View(repDetailed.ToModel());
        }


        #region  测试

        public ActionResult Summernote(string Id)
        {
            //将ProductId通过model传到前端
            RepDetailedModel model = new RepDetailedModel();
            model.ProductId = Id;
            //返回功能性需求Model
            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Summernote(RepDetailedModel repDetailed)
        {
            if (ModelState.IsValid)
            {
                repDetailed.RepDetailedId = Guid.NewGuid().ToString();
                repDetailed.CreateAt = DateTime.Now;
                string userId = HttpContext.Session["UserId"] as string;
                repDetailed.UserId = userId;
                //将Models类转换成Domain类
                RepDetailed toEntity = repDetailed.ToEntity();
                DBCRUD.Create(toEntity);
                return RedirectToAction("Details", "ProductInfo", new { id = repDetailed.ProductId });
            }
            return View(repDetailed);
        }
        #endregion

    }
}

REQM/Views/RepDetailed/Create.cshtml
@model RepDetailedModel

@{
    ViewBag.Title = "创建功能性需求";
    Layout = "../Shared/_LayoutAdminLTE.cshtml";
}

<head>
    <!--summernote-->
    <link href="~/Content/summernote/summernote.css" rel="stylesheet" />
    <script src="~/Content/summernote/summernote.js"></script>
    <script src="~/Content/summernote/summernote-zh-CN.js"></script>
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- 内容标题 -->
    <section class="content-header">
        <h1>
            创建功能性需求
            <small>产品管理</small>
        </h1>
        <!--  导航地图  -->
        <ol class="breadcrumb">
            <li><a href="~/Product/Index"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">产品管理</li>
        </ol>
    </section>

    <!-- 内容Panel -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            @*<div class="box-header with-border">
                    <h3 class="box-title">创建新产品</h3>
                </div>*@
            <div class="box-body">
                <!--  这是写入要展示的内容  -->
                <div class="form-group">

                    @Html.EditorFor(m => m.RepName, new { htmlAttributes = new { @class = "form-control", placeholder = "请输入功能性需求名称" } })
                    @Html.ValidationMessageFor(m => m.RepName, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">

                    @Html.EditorFor(m => m.Priority, new { htmlAttributes = new { @class = "form-control", placeholder = "优先级" } })
                    @Html.ValidationMessageFor(m => m.Priority, "", new { @class = "text-danger" })

                </div>
                @Html.HiddenFor(Model => Model.ProductId)
                @Html.HiddenFor(Model => Model.RepDescribe)
                <div class="form-group">

                    <div id="summernote" placeholder="请输入产品功能性需求"></div>
                    @Html.ValidationMessageFor(m => m.RepDescribe, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">

                    @Html.TextAreaFor(m => m.Revision, new { @class = "form-control", rows = 5, placeholder = "请输入修改记录" })
                    @Html.ValidationMessageFor(m => m.Revision, "", new { @class = "text-danger" })

                </div>

                <div>
                    <button type="submit" class="btn btn-primary btn-block" id="btnRegister">保存</button>
                </div>
                <!--  这是写入要展示的内容  -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
}



@section scripts{
    <!-- 内部javascript -->
    <script>

        $(document).ready(function () {

            var placeholder = $("#summernote").attr("placeholder") || '';//设置输入提示
            var url = $("#summernote").attr("action") || '';//设置上传图片的url
            $("#summernote").summernote({
                lang: 'zh-CN',
                placeholder: placeholder,
                minHeight: 300,
                maxHeight: 800,
                dialogsFade: true,// 设置滑动效果Add fade effect on dialogs
                dialogsInBody: true,// 设置窗口显示位置Dialogs can be placed in body, not in
                disableDragAndDrop: false,//设置拖拽
                callbacks: {
                    onImageUpload: function (files) {
                        $(files).each(function () {
                            var file = this;
                            var data = new FormData();
                            data.append("file", file);
                            //ajax上传图片
                            $.ajax({
                                url: url,
                                type: "post",
                                data: data,
                                dataType: "json",
                                cache: false,
                                contentType: false,
                                processData: false,
                                success: function (response) {
                                    var jsonObj = JSON.parse(response);  // JSON.parse(); 方法
                                    var jsonObj = JSON.parse(response);  // JSON.parse(); 方法
                                    var imgNode = document.createElement('img');
                                    imgNode.setAttribute('src', jsonObj.result);
                                    $("#summernote").summernote('insertNode', imgNode);
                                },
                                error: function (response) {
                                }
                            });
                        });
                    }
                }
            });

            //初始化summernote的值
            var encodevalue = $("#RepDescribe").val();
            //var decodevalue = htmlDecode(encodevalue);
            $('#summernote').summernote('code', encodevalue);

        });

        //设置表单数值
        $("form").submit(function (e) {
            var makrup = $("#summernote").summernote('code');

            //var encodevalue = htmlEncode(makrup);
            $("#RepDescribe").val(makrup);
        });

    </script>
}

REQM/Views/RepDetailed/Details.cshtml
@model RepDetailedModel

@{
    ViewBag.Title = Model.RepName + "详情";
    Layout = "../Shared/_LayoutAdminLTE.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- 内容标题 -->
    <section class="content-header">
        <h1>
            @Model.RepName
            <small>需求详情</small>
        </h1>
        <!--  导航地图  -->
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="~/RepDetailed/Index"><i class="fa fa-dashboard"></i> 产品管理</a></li>
            <li class="active">功能性需求</li>
        </ol>
    </section>

    <!-- 内容Panel -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.ProductId</h3>
            </div>
            <div class="box-body">
                <!--  这是写入要展示的内容开始  -->
                <div>
                    <!--详情标题-->
                    <h3>
                        @Html.DisplayFor(m => m.RepName) (优先级别：@Html.DisplayFor(m => m.Priority))
                    </h3>
                    <p classblog-post-meta">@Model.CreateAt &nbsp&nbspby:<a href="#">@Model.DisplayName</a></p>
                    <div>
                        @Html.LabelFor(m => m.RepDescribe)
                        @Html.Raw(HttpUtility.HtmlDecode(@Model.RepDescribe))
                    </div>

                    @if (Model.Revision != null)
                    {
                        <hr />
                        @Html.LabelFor(m => m.Revision)
                        <p classblog-post-meta">@Model.UpdateAt &nbsp&nbspby:@Model.DisplayName</p>
                        @Html.Raw(HttpUtility.HtmlDecode(@Model.Revision))
                    }


                </div>
                <!--  这是写入要展示的内容结束  -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
}




REQM/Views/RepDetailed/Edit.cshtml
@model RepDetailedModel
@{
    ViewBag.Title = Model.RepName + "编辑";
    Layout = "../Shared/_LayoutAdminLTE.cshtml";
}

<head>
    <!--summernote-->
    <link href="~/Content/summernote/summernote.css" rel="stylesheet" />
    <script src="~/Content/summernote/summernote.js"></script>
    <script src="~/Content/summernote/summernote-zh-CN.js"></script>
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- 内容标题 -->
    <section class="content-header">
        <h1>
            @Model.RepName
            <small>功能性需求编辑</small>
        </h1>
        <!--  导航地图  -->
        <ol class="breadcrumb">
            <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="~/ProductInfo/Index"><i class="fa fa-dashboard"></i>产品管理</a></li>
            <li class="active">功能性需求编辑</li>
        </ol>
    </section>

    <!-- 内容Panel -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            @*<div class="box-header with-border">
                    <h3 class="box-title">创建新产品</h3>
                </div>*@
            <div class="box-body">
                <!--  这是写入要展示的内容  -->
                <div class="form-group">

                    @Html.EditorFor(m => m.RepName, new { htmlAttributes = new { @class = "form-control", placeholder = "请输入功能性需求名称" } })
                    @Html.ValidationMessageFor(m => m.RepName, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">

                    @Html.EditorFor(m => m.Priority, new { htmlAttributes = new { @class = "form-control", placeholder = "优先级" } })
                    @Html.ValidationMessageFor(m => m.Priority, "", new { @class = "text-danger" })

                </div>

                @Html.HiddenFor(Model => Model.ProductId)
                @Html.HiddenFor(Model => Model.RepDetailedId)
                @Html.HiddenFor(Model => Model.RepDescribe)
                @Html.HiddenFor(Model => Model.CreateAt)
                @Html.HiddenFor(Model => Model.UserId)

                <div class="form-group">

                    <div id="summernote" placeholder="请输入产品功能性需求"></div>
                    @Html.ValidationMessageFor(m => m.RepDescribe, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">

                    @Html.TextAreaFor(m => m.Revision, new { @class = "form-control", rows = 5, placeholder = "请输入修改记录" })
                    @Html.ValidationMessageFor(m => m.Revision, "", new { @class = "text-danger" })

                </div>

                <div>
                    <button type="submit" class="btn btn-primary btn-block" id="btnRegister">保存</button>
                </div>
                <!--  这是写入要展示的内容  -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
}





@using (Html.BeginForm("Edit", "RepDetailed", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



}

@section scripts{
    <!-- 内部javascript -->
    <script>

        $(document).ready(function () {

            var placeholder = $("#summernote").attr("placeholder") || '';//设置输入提示
            var url = $("#summernote").attr("action") || '';//设置上传图片的url
            $("#summernote").summernote({
                lang: 'zh-CN',
                placeholder: placeholder,
                minHeight: 300,
                maxHeight: 800,
                dialogsFade: true,// 设置滑动效果Add fade effect on dialogs
                dialogsInBody: true,// 设置窗口显示位置Dialogs can be placed in body, not in
                disableDragAndDrop: false,//设置拖拽
                callbacks: {
                    onImageUpload: function (files) {
                        $(files).each(function () {
                            var file = this;
                            var data = new FormData();
                            data.append("file", file);
                            //ajax上传图片
                            $.ajax({
                                url: url,
                                type: "post",
                                data: data,
                                dataType: "json",
                                cache: false,
                                contentType: false,
                                processData: false,
                                success: function (response) {
                                    var jsonObj = JSON.parse(response);  // JSON.parse(); 方法
                                    var jsonObj = JSON.parse(response);  // JSON.parse(); 方法
                                    var imgNode = document.createElement('img');
                                    imgNode.setAttribute('src', jsonObj.result);
                                    $("#summernote").summernote('insertNode', imgNode);
                                },
                                error: function (response) {
                                }
                            });
                        });
                    }
                }
            });

            //初始化summernote的值
            var encodevalue = $("#RepDescribe").val();
            //var decodevalue = htmlDecode(encodevalue);
            $('#summernote').summernote('code', encodevalue);

        });

        //设置表单数值
        $("form").submit(function (e) {
            var makrup = $("#summernote").summernote('code');

            //var encodevalue = htmlEncode(makrup);
            $("#RepDescribe").val(makrup);
        });

    </script>

}

REQM/Views/RepDetailed/Index.cshtml
@model List<RepDetailed>

@{
    Layout = "../Shared/_LayoutAdminLTE.cshtml";
}


<!-- 内容标题 -->
<section class="content-header">
    <h1>
        功能性需求列表
        <small>产品管理</small>
    </h1>
    <!--  导航地图  -->
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="~/ProductInfo/Index"><i class="fa fa-dashboard"></i> 产品管理</a></li>
        <li class="active">功能性需求</li>
    </ol>
</section>

<!-- 内容Panel -->
<section class="content">
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"></h3>
            <div class="pull-left">
                <a class="btn btn-primary" href="~/RepData/Create"><i class="fa fa-plus"></i> 创建需求</a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-condensed table-hover table-striped">
                <tr>
                    <td align="center">@Html.LabelFor(m => m[0].RepName)</td>
                    <td align="center">@Html.LabelFor(m => m[0].Priority)</td>
                    <td align="center">@Html.LabelFor(m => m[0].CreateAt)</td>
                    <td align="center"><label>创建/修改人</label></td>
                    <td align="center"><label>操作</label></td>
                </tr>
                @foreach (var repDetaileds in Model)
                {
                    <tr>
                        <td align="center"><a href="@Url.Content("~/RepDetailed/Details/"+repDetaileds.RepDetailedId)">@Html.DisplayFor(m => repDetaileds.RepName)</a></td>
                        <td align="center"><a href="@Url.Content("~/RepDetailed/Details/"+repDetaileds.RepDetailedId)">@Html.DisplayFor(m => repDetaileds.Priority)</a></td>
                        <td align="center"><a href="@Url.Content("~/RepDetailed/Details/"+repDetaileds.RepDetailedId)">@Html.DisplayFor(m => repDetaileds.CreateAt)</a></td>
                        <td align="center"><a href="@Url.Content("~/RepDetailed/Details/"+repDetaileds.RepDetailedId)">@Html.DisplayFor(m => repDetaileds.user.DisplayName)</a></td>
                        <td align="center">
                            <a href="@Url.Content("~/RepDetailed/Details/"+repDetaileds.RepDetailedId)">详情</a> |
                            <a href="@Url.Content("~/RepDetailed/Edit/"+repDetaileds.RepDetailedId)">编辑</a> |
                            <a href="@Url.Content("~/RepDetailed/Delete/"+repDetaileds.RepDetailedId)">删除</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->

</section>

REQM/Views/RepDetailed/Summernote.cshtml
@model RepDetailedModel

@{
    ViewBag.Title = "Summernote";
}

<div id="summernote">这是Summernote富文本框</div>


@*<script type="text/javascript">
        //加载编辑器
        $(document).ready(function () {
            $("#summernote").summernote({
                height: 400,
                minHeight: 300,
                maxHeight: 500,
                focus: true,
                lang: "zh-CN",
                //重写图片上传
                onImageUpload: function (files, editor, $editable) {
                    sendFile(files[0], editor, $editable);
                }
            });
        });
        //图片上传
        function sendFile(file, editor, $editable) {
            var filename = false;
            try{
                filename=false['name'];
            } catch (e) {
                filename = false;
            }
            if (!filename) {
                $(".note-alarm").remove();
            }

            //以上防止在编辑器内拖拽引发第二次上传导致的提示错误
            data = new FormData();
            data.append("file", "file");
            data.append("key", "filename");//唯一性参数

            $.ajax({
                data: data,
                type: "POST",
                url: "",
                cache: false,
                contentType: false,
                success: function (url) {
                    if (url == '200') {
                        alert("上传失败！")
                        return;
                    } else {
                        alert("上传成功！")
                    }
                    //alert(url);
                    editor.insertImage($editable, url)
                    //setTimeout(funtion(){$(".note-alarm").remove();},3000);
                },
                error: function () {
                    alert("上传失败！");
                    return;
                    //setTimeout(funtion(){$(".note-alarm").remove();},3000);
                }
            });
        }

        //var encodevalue = $("#RepDescribe").val();
        ////var decodevalue = htmlDecode(encodevalue);
        //$("#summernote").summernote('code', encodevalue);

        ////给编辑器赋值
        //var makrup = $('#summernote').summernote('code');
        ////var encodevalue = htmlEncode(makrup);
        //$("#RepDescribe").val(makrup);
    </script>*@

@*<script>
    $(document).ready(function () {
        $('.summernote').summernote();
    })
</script>*@


<script type="text/javascript">

    $(document).ready(function () {

        /* function sendFile(file, editor,welEditable) {
         console.log("file="+file);
         console.log("editor="+editor);
         console.log("welEditable="+welEditable);
          data = new FormData();
          data.append("blog_image[image]", file);
          $.ajax({
           url: 'blog_images.jsp',
           data: data,
           cache: false,
           contentType: false,
           processData: false,
           type: 'POST',
           success: function(data){
            editor.insertImage(welEditable, data.url);
           }
          });
         }
        */
        $('#summernote').summernote({
            height: 300, /*高さを指定*/
            lang: 'zh-CN', // default: 'en-US'
            focus: true,
            toolbar: [
             ['style', ['bold', 'italic', 'underline', 'clear']],
             ['fontsize', ['fontsize']],
             ['color', ['color']],
             ['para', ['ul', 'ol', 'paragraph']],
             ['height', ['height']],
             ['insert', ['picture', 'video']]
            ],
            /* image: {

                selectFromFiles: '选择文件'

               }, */
            /*onImageUpload: function(files, editor, welEditable) {
              sendFile(files[0], editor,welEditable);
            }*/
            onImageUpload: function (files, editor, $editable) {
                sendFile(files[0], editor, $editable);
            }


        });
    });


    function sendFile(file, editor, $editable) {
        $(".note-toolbar.btn-toolbar").append('正在上传图片');
        var filename = false;
        try {
            filename = file['name'];
            alert(filename);
        } catch (e) { filename = false; }
        if (!filename) { $(".note-alarm").remove(); }
        //以上防止在图片在编辑器内拖拽引发第二次上传导致的提示错误
        var ext = filename.substr(filename.lastIndexOf("."));
        ext = ext.toUpperCase();
        var timestamp = new Date().getTime();
        var name = timestamp + "_" + $("#summernote").attr('aid') + ext;
        //name是文件名，自己随意定义，aid是我自己增加的属性用于区分文件用户
        data = new FormData();
        data.append("file", file);
        data.append("key", name);
        data.append("token", $("#summernote").attr('token'));

        $.ajax({
            data: data,
            type: "POST",
            url: "/summernote/fileupload", //图片上传出来的url，返回的是图片上传后的路径，http格式
            contentType: "json",
            cache: false,
            processData: false,
            success: function (data) {
                //data是返回的hash,key之类的值，key是定义的文件名
                alert(data);
                //把图片放到编辑框中。editor.insertImage 是参数，写死。后面的http是网上的图片资源路径。
                //网上很多就是这一步出错。
                $('#summernote').summernote('editor.insertImage', "http://res.cloudinary.com/demo/image/upload/butterfly.jpg");

                $(".note-alarm").html("上传成功,请等待加载");
                setTimeout(function () { $(".note-alarm").remove(); }, 3000);
            },
            error: function () {
                $(".note-alarm").html("上传失败");
                setTimeout(function () { $(".note-alarm").remove(); }, 3000);
            }
        });
    }

</script>

<script>
    var HelloButton = function (context) {
        var ui = $.summernote.ui;

        // create button
        var button = ui.button({
            contents: '<i class="fa fa-child" /> Hello',
            tooltip: 'hello',
            click: function () {
                // invoke insertText method with 'hello' on editor module.
                context.invoke('editor.insertText', 'hello');
            }
        });

        return button.render();   // return button as jquery object
    }
</script>